services:
  wordpress:
    image: wordpress:latest
    ports:
      - "8080:80"
    networks:
      - red_utn
    depends_on:
      - db
    environment:
      WORDPRESS_DB_HOST: db:3306
      WORDPRESS_DB_USER: wp_user
      WORDPRESS_DB_PASSWORD: wp_password
      WORDPRESS_DB_NAME: wp_database

  db:
    image: mariadb:latest
    networks:
      - red_utn
    environment:
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
      MYSQL_DATABASE: wp_database
      MYSQL_ROOT_PASSWORD: root_secret
    volumes:
      - db_data:/var/lib/mysql

networks:
  red_utn:
    driver: bridge

volumes:
  db_data: